### ISSUE TITLE
What license is this code under?

### ISSUE THREAD

**Issue by MoralCode** [aehaq/Movie-voter#2]
Hello, Thank you so much for creating this!

I was wondering what license you would prefer people follow with regard to this codebase?

**Comment by aehaq** [comment]
Hi there,

I started this project utilizing some code from a previous project I had done that used the MIT License. I have now added the MIT License to this as well. 

Thanks for your interest! I hope you don't mind the lack of documentation. Normally I am very thorough, but I made this in a hurry because I was having a bunch of friends over for a movie night and wanted to quickly set up a way for them to vote on a selection.

When I have free time, I may jump back in to this project in the future now that it is back on my radar. In the meantime, feel free to fork this project and credit the source!
